### ISSUE TITLE
New resource for xActiveDirectory: xADSiteLink

### ISSUE THREAD

**Issue by Hindy-UK** [PowerShell/xActiveDirectory#148]
I'd like to contribute a new resource to this module:

- xADSiteLink - creates and manages Active Directory site links

Opening an issue before forking as per the contribution guidelines.

(Edited to split resources into seperate issues as requested below)

**Comment by iainbrighton** [comment]
Hi @Hindy-UK - great idea 👍. It might be better to open an issue each resource so that the schema for each resource can be discussed separately?

**Comment by Hindy-UK** [comment]
Hi,

Will do. I've edited this issue and will open 2 new issues for the other resources.

**Comment by Hindy-UK** [comment]
With the exception of one issue that I'm struggling with, I have xADSiteLink ready to go. Even though the resource works properly via the pull server, it is failing Get-DscConfiguration and when calling Get-TestResource directly with a general error/CimException. 

This only occurs when using the optional ReplicationSchedule parameter, which results in the raw schedule from an ActiveDirectorySchedule object being added to the targetResource hash table as a bool array. Code can be seen here in lines 181 and 188:
 [https://github.com/Hindy-UK/xActiveDirectory/blob/working/DSCResources/MSFT_xADSiteLink/MSFT_xADSiteLink.psm1](url)

I'll continue looking into it, but if anyone else is able to take a look and see if they can spot the issue it'd be a great help.

**Comment by solbirn** [comment]
@Hindy-UK 
Appears the issue is occurring due to a mismatch of return between Get-TargetResource and the schema. 

The **ReplicationSchedule** which is defined as type **String[]** in the schema (two dimensional [string] array) but is being returned in the $targetResource hashtable as a straight up ActiveDirectorySchedule.RawSchedule which is of type **Boolean[,,]** (three dimensional [boolean] array). 

Would probably be best to serialize it back into the **String[]** format just like the schema/resource function(s) parameter, before adding it into the return hashtable.
