### ISSUE TITLE
Repeated runs - Passwords reset

### ISSUE THREAD

**Issue by mattcanty** [PowerShell/xActiveDirectory#219]
Wondering what the approach is when using this in an environment endeavouring for everything-as-code.

I have AD set up, and wish to store configuration of users and groups as code.

This means that the DSC will run periodically, eg when it has changed. It appears that this is resetting the passwords of any users who have changed them.

1. Users should be able to change their passwords.
2. I want to set a strong password automatically, which will be distributed to them.

Are there any guides or approaches I should take?

At the moment I am setting up users with the following property:

`Password = New-Object System.Management.Automation.PSCredential ("matt.canty", $DefaultPassword)`

**Comment by johlju** [comment]
Thanks for reporting this.

Did not know it did this, apparently it tests the password here in the `Test-TargetResource` function. I think this test should only be done if `$CannotChangePassword` equals to `$true`. If ´$CannotChangePassword` equals to `$false` (the default value) this test cannot be done, since the password can be changed on the user account.

https://github.com/PowerShell/xActiveDirectory/blob/9f9f19932e03978ae7885109c378f69f29165e40/DSCResources/MSFT_xADUser/MSFT_xADUser.psm1#L552-L569

**Comment by johlju** [comment]
Labeling this as a bug, and a breaking change since all configuration will need to add `CannotChangePassword = $true` to use the same check as was done by default previously.

**Comment by ronhowe** [comment]
I support this implementation.  I am deploying users with xADUser.  I have to add them to configuration, deploy, then take them out and redeploy so that they don't keep getting their password set back to the default.
