### ISSUE TITLE
xADUser: Unable to add ChangePasswordAtLogon to the New-ADUser cmdlet

### ISSUE THREAD

**Issue by Chirag1233** [PowerShell/xActiveDirectory#246]
Hi guys I am trying to add the ChangePasswordAtLogon Parameter to the new-aduser so everytime a new users gets created they have to reset the password at first logon. do you know why I can't just simply replace New-ADUser @newADUserParams -SamAccountName $UserName;  to  New-ADUser @newADUserParams -SamAccountName $UserName -ChangePasswordAtLogon $true -Verbose; or is there any other way I can change add the ChangePasswordAtLogon value so it only became available when a new users get created and does not touch any of the existing users.

**Comment by johlju** [comment]
There are no parameter for it. But using that together with `$PasswordNeverResets` could probably work. But I think the first intention with this resource was to create accounts that should be able to be used right away. But your scenario might be able to be covered to. 
If you get it working, please send in a PR. In the mean time I label this so that someone in the community can work on this, or answer if it could be possible.
