### ISSUE TITLE
xADObjectRDN - New resource proposal

### ISSUE THREAD

**Issue by Torch02** [PowerShell/xActiveDirectory#305]
### Description
Resource to set an object's location within the directory

### Proposed properties
**[String] ObjectName** _(Key)_:  Name of the Active Directory object to manage.
**[String] Path** _(Write)_: Specifies the X.500 path of the Organizational Unit (OU) or container where the object is located.

### Special considerations or limitations
The *Path* parameter in xADComputer, xADGroup, and xADUser only allow the parent OU/container to be set at creation. This resource (likely backed by the Move-ADObject cmdlet) would set the directory location for existing resources.

The use cases I can think of for this resource would be:

* Managing objects in a non-greenfield environment
* Managing computer objects that were joined to the domain in ways that aren't the xADComputer resource
* Moving objects from a "staging" OU to a "prod" OU after certain build/deployment steps
* Enforcing company policy for certain objects 

This could be useful for auditing where the LCM's ConfigurationMode is **ApplyAndMonitor** or for strict configuration control when the LCM's ConfigurationMode is **ApplyAndAutoCorrect**.

**Comment by johlju** [comment]
Thank you for sending in this proposal. 🙂 

How would this extend outside of the existing functionality in the existing resources that already have the ability to move "itself". Why would you just want to move an object and not assert that the object exists and have the correct properties? 
Do you have a scenario where this resource would only work, and the existing or new resource managing a particular object would not work?

**Notes / Questions**

`ObjectName` should be an identity, like a DN to support multiple domain where the two objects can have the same name? 

Since other resources today are using `Move-ADObject` to move an object, if it is moved out the parent container where it was created, then we would get a ping-pong behavior is this resource would be used in the same configuration as any resource using `Move-ADObject`. So if we create this resource then we should remove the "move" functionality out of the other resources and only have it in this new resource. `Path` in the other resources is only used during the creation, and not enforced.

> Moving objects from a "staging" OU to a "prod" OU after certain build/deployment steps

This means neither configuration is never enforced, otherwise another configuration would move back the object to "staging" again making a ping-pong behavior. It sounds like a scenario that maybe DSC should not be used for, or existing resource could be used for?

**Comment by Torch02** [comment]
Somehow I got it stuck in my head (misread something, mis-assumed something) that the Path parameter was only for object creation. After both looking at the source code and doing some testing, that parameter on those resources works fine for what I was intending. Closing the issue.
