### ISSUE TITLE
xADDomain and xADDomainController: Ability to enable/disable Global Catalog

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xActiveDirectory#75]
Currently all DC's promoted using xADDomain and xADDomainController are set as GC's.

This is fine for the first DC on in a domain (or site), but usually undesirable for additional DC's added to a domain (usually only one GC per site is recommended).

Could we add a parameter to disable GC when promoting a DC? If the DC is already promoted then this switch would need to disable GC on the DC by calling something like this:
http://blogs.msmvps.com/richardsiddaway/2012/03/18/enable-global-catalog/

This probably only needs to be added to the xADDomainController resource because there must always be at least one GC in a domain so the xADDomain should always create a GC, although, if the first DC on the domain (that was promoted using xADDomain) needed to have the GC removed then xADDomain should also support enabling/disabling the GC. Thoughts?

I don't think that this needs to be a tri-state switch (like the DNS one).

**Comment by Merto410** [comment]
Couple comments.  Be careful about GC placement without planning your FSMO holders.  The scenario you paint would be bad in a multi-domain forest since the infra master would be a GC and your other DC's would not.
I think this should be an option, but also I think your info on recommendations is outdated.  In single domain forests it is expected that all DC's will be GC's (there is no impact either way really so the option isn't necessary in that scenario), and even in multi-domain forests the recommendation is to have all DC's be GC's unless specific conditions apply.  VIA https://technet.microsoft.com/en-us/library/cc732877%28v=ws.10%29.aspx?f=255&MSPPError=-2147217396 
"
**In most cases, it is recommended that you include the global catalog when you install new domain controllers**. The following exceptions apply:

    Limited bandwidth: In remote sites, if the wide area network (WAN) link between the remote site and the hub site is limited, you can use universal group membership caching in the remote site to accommodate the logon needs of users in the site.

    Infrastructure operations master role incompatibility: Do not place the global catalog on a domain controller that hosts the infrastructure operations master role in the domain unless all domain controllers in the domain are global catalog servers or the forest has only one domain.
"

**Comment by Merto410** [comment]
I am submitting a pull request with the IsGlobalCatalog option for the xAdDomainController.
