### ISSUE TITLE
Add possibility to install secondary DC in different AD Site

### ISSUE THREAD

**Issue by josch710** [PowerShell/xActiveDirectory#76]
Please add optional parameter to install secondary DC into a specific AD Site

**Comment by iainbrighton** [comment]
@josch710 This will presumably need to go into the xADDomainController resource?

**Comment by josch710** [comment]
@iainbrighton Yes - would say so...

**Comment by iainbrighton** [comment]
@josch710 Is the assumption with the `xADDomainController` resource, that the target AD site already exists? If not, I don't think creating sites should be the responsibility of the `xADDomainController` resource and we would need to log an issue to get a `xADSite` resource put together.

**Comment by josch710** [comment]
@iainbrighton : Yes - the target AD Site should already exist - so it will install the Domain Controller as a secondary DC into an already existing Domain structure

**Comment by gordonbondon** [comment]
This is what we need in our environment. I'm currently working on adding Site support to `xADDomainController`. I might submit a PR in a while.

**Comment by gordonbondon** [comment]
While working on this feature I've noticed that I need to add handling on whether  domain was not found or domain controller was not found. Because [this](https://github.com/PowerShell/xActiveDirectory/blob/dev/DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1#L56) catch block catches both errors. Should i add this in the same brunch with Site property or in separate one?
